LrMetadataBuilder/Models/League.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;

namespace LrMetadataBuilder.Models
{
    public class League
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "League Name")]
        public string Name { get; set; }    
    }
}

LrMetadataBuilder/ViewModels/LeagueViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using LrMetadataBuilder.Models;

namespace LrMetadataBuilder.ViewModels
{
    public class LeagueViewModel
    {
        public int Id;

        [Display(Name= "League Name")]
        [Required(ErrorMessage = "Please provide a League Name")]
        public string Name;
        public string Title { get; set; }
        public List<League> Leagues;
        public League League;
    }
}

LrMetadataBuilder/Controllers/LeagueController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LrMetadataBuilder.Models;
using LrMetadataBuilder.ViewModels;
using Microsoft.EntityFrameworkCore.Query.Expressions;

namespace LrMetadataBuilder.Controllers
{
    public class LeagueController : Controller
    {
        private readonly ILeagueRepository _leagueRepository;

        public LeagueController(ILeagueRepository leagueRepository)
        {
            _leagueRepository = leagueRepository;
        }

        // GET: League
        public IActionResult Index()
        {
            var leagues = _leagueRepository.GetAllLeagues().OrderBy(l => l.Name);

            var leagueViewModel = new LeagueViewModel()
            {
                Title = "Manage Leagues",
                Leagues = leagues.ToList()
            };
            return View(leagueViewModel);
        }

        // GET: League/Details/5
        public IActionResult Details(int? id)
        {
            if (id != null)
            {
                var league = _leagueRepository.GetLeagueById((int)id);
                if (league != null)
                {
                    var leagueViewModel = new LeagueViewModel();
                    leagueViewModel.Id = league.Id;
                    leagueViewModel.Name = league.Name;
                    
                    return View(leagueViewModel);
                }

                return NotFound();
            }

            return BadRequest();
 
        }

        // GET: League/Create
        public IActionResult Create()
        {
            var leagueViewModel = new LeagueViewModel();
            return View(leagueViewModel);
        }

        // POST: League/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name")] LeagueViewModel leagueViewModel)
        {
            if (ModelState.IsValid)
            {
                var league = new League(){Name = leagueViewModel.Name};
                _leagueRepository.Add(league);
                _leagueRepository.Save();
                return RedirectToAction("Index");
            }
            return View(leagueViewModel);
        }

        // GET: League/Edit/id
        public IActionResult Edit(int id)
        {
            var league = _leagueRepository.GetLeagueById(id);
            if (league == null)
            {
                return NotFound();
            }
           
            var viewModel = new LeagueViewModel()
            {
                Name = league.Name,
                Id = league.Id
            };
            return View(viewModel);
        }

        // POST: League/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name")] LeagueViewModel viewModel)
        {
            if (id != viewModel.League.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var league = _leagueRepository.GetLeagueById(id);
                    if (league == null)
                    {
                        return NotFound();
                    }

                    league.Name = viewModel.Name;

                    _leagueRepository.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeagueExists(viewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            return View("Edit");
        }

        // GET: League/Delete/5
        public IActionResult Delete(int id)
        {

            var league = _leagueRepository.GetLeagueById(id);
            if (league == null)
            {
                return NotFound();
            }

            return View(league);
        }

        // POST: League/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var league = _leagueRepository.GetLeagueById(id);
            _leagueRepository.Delete(league);
            _leagueRepository.Save();
            return RedirectToAction("Index");
        }

        private bool LeagueExists(int id)
        {
            var league = _leagueRepository.GetLeagueById(id);
            if (league == null)
            {
                return false;
            }
            else
            {
                return true;
            }
            
        }
    }
}

LrMetadataBuilder/Views/League/Create.cshtml
@model LeagueViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>League</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LrMetadataBuilder/Views/League/Delete.cshtml
@model LrMetadataBuilder.Models.League

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LrMetadataBuilder/Views/League/Details.cshtml
@model LeagueViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LrMetadataBuilder/Views/League/Edit.cshtml
@model League

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>League</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LrMetadataBuilder/Views/League/Index.cshtml
@model LeagueViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Leagues
                </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var league in Model.Leagues) {
        <tr>
            <td>
                @league.Name
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@league.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@league.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@league.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

LrMetadataBuilder/Views/League/List.cshtml
@model LeagueViewModel

<div>
    <h2>Manage Leagues</h2>
    <p>To update any of the league details, click on the EDIT link next to the league name. </p>
    <ul>
        @foreach (var league in Model.Leagues)
        {
            <li>@league.Name <a asp-controller="League" asp-action="Edit">EDIT</a></li>
        }
    </ul>
</div>